### ISSUE TITLE
[0.3.0] Stuck on Windows 10 and VirtualBox

### ISSUE THREAD

**Issue by gtirloni** [jimmidyson/minishift#30] opened 2016-07-19 17:30 UTC
minishift 0.3.0
Windows 10 64-bit
VirtualBox 5.0.26

Stuck at:

```
>minishift-windows-amd64.exe start --cpus=2 --memory=4096 --vm-driver=virtualbox
Starting local OpenShift cluster...
```

![minishift_vbox_console](https://cloud.githubusercontent.com/assets/5902830/16959783/fd101540-4dbc-11e6-896f-0dc76983225a.png)

Initially it did not work but showed that `openshift start` had been attempted in the VM. `minishift start` finished and said to connect to http://192.168.99.100:8433. That redirected to a 10.x.x.x address and didn't work.

After I disabled firewall and anti-virus (Kaspersky), it got to the state I'm reporting in this issue where `minishift start --cpus=2 --memory=4096 --vm-driver=virtualbox` does not finish (in 5-10min at least).

**Comment by jimmidyson** [comment] 2016-07-20 08:26
Can you please share output of `minishift logs`? Unfortunately I don't have a Windows env to replicate this on so your help in diagnosing the issue would be very welcome :)

**Comment by gtirloni** [comment] 2016-07-20 17:31
```
>minishift-windows-amd64.exe start --cpus=2 --memory=4096 --vm-driver=virtualbox
Starting local OpenShift cluster...
OpenShift is available at https://192.168.99.100:8443.
oc is now configured to use the cluster.
Run this command to use the cluster:
oc login --username=admin --password=admin --insecure-skip-tls-verify


>minishift-windows-amd64.exe logs

==> /var/lib/minishift/openshift.err <==

==> /var/lib/minishift/openshift.out <==
W0720 17:26:44.031302    2938 start_master.go:271] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
W0720 17:26:44.031332    2938 start_master.go:271] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
I0720 17:26:44.035240    2938 admission.go:36] Admission plugin "ProjectRequestLimit" is not configured so it will be disabled.
I0720 17:26:44.035254    2938 admission.go:34] Admission plugin "PodNodeConstraints" is not configured so it will be disabled.
I0720 17:26:44.047630    2938 plugins.go:71] No cloud provider specified.
I0720 17:26:44.047644    2938 admission.go:30] Admission plugin "RunOnceDuration" is not configured so it will be disabled.
I0720 17:26:44.047663    2938 admission.go:34] Admission plugin "PodNodeConstraints" is not configured so it will be disabled.
I0720 17:26:44.047671    2938 admission.go:42] Admission plugin "ClusterResourceOverride" is not configured so it will be disabled.
I0720 17:26:44.048366    2938 genericapiserver.go:84] Adding storage destination for group
I0720 17:26:44.048391    2938 genericapiserver.go:84] Adding storage destination for group extensions
I0720 17:26:44.048412    2938 start_master.go:384] Starting master on 0.0.0.0:8443 (v1.3.0-alpha.2)
I0720 17:26:44.048416    2938 start_master.go:385] Public master address is https://10.0.2.15:8443
I0720 17:26:44.048436    2938 start_master.go:389] Using images from "openshift/origin-<component>:v1.3.0-alpha.2"
E0720 17:26:44.052329    2938 cacher.go:221] unexpected ListAndWatch error: pkg/storage/cacher.go:164: Failed to list *api.ClusterPolicy: client: etcd cluster is unavailable or misconfigured
I0720 17:26:44.054080    2938 run.go:61] Started etcd at 10.0.2.15:4001
I0720 17:26:44.101572    2938 run_components.go:224] Using default project node label selector:
W0720 17:26:44.360176    2938 controller.go:262] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[]} [{[{10.0.2.15 <nil>}] [] [{https 8443 TCP} {dns 8053 UDP} {dns-tcp 8053 TCP}]}]}
I0720 17:26:44.611422    2938 master.go:270] Started Kubernetes API at 0.0.0.0:8443/api/v1
I0720 17:26:44.611444    2938 master.go:270] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/extensions/v1beta1
I0720 17:26:44.611447    2938 master.go:270] Started Origin API at 0.0.0.0:8443/oapi/v1
I0720 17:26:44.611449    2938 master.go:270] Started OAuth2 API at 0.0.0.0:8443/oauth
I0720 17:26:44.611452    2938 master.go:270] Started Web Console 0.0.0.0:8443/console/
I0720 17:26:44.611454    2938 master.go:270] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
I0720 17:26:44.716969    2938 ensure.go:224] No cluster policy found.  Creating bootstrap policy based on: openshift.local.config/master/policy.json
I0720 17:26:45.737798    2938 ensure.go:209] Created default security context constraint privileged
I0720 17:26:45.738997    2938 ensure.go:209] Created default security context constraint nonroot
I0720 17:26:45.740221    2938 ensure.go:209] Created default security context constraint hostmount-anyuid
I0720 17:26:45.741382    2938 ensure.go:209] Created default security context constraint hostaccess
I0720 17:26:45.742879    2938 ensure.go:209] Created default security context constraint restricted
I0720 17:26:45.744618    2938 ensure.go:209] Created default security context constraint anyuid
I0720 17:26:45.745983    2938 ensure.go:209] Created default security context constraint hostnetwork
W0720 17:26:47.728617    2938 run_components.go:202] Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients
I0720 17:26:47.728771    2938 log.go:11] skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:8053 [rcache 0]
I0720 17:26:47.728779    2938 log.go:11] skydns: ready for queries on cluster.local. for udp4://0.0.0.0:8053 [rcache 0]
I0720 17:26:47.829123    2938 run_components.go:219] DNS listening at 0.0.0.0:8053
I0720 17:26:47.830953    2938 start_master.go:530] Controllers starting (*)
I0720 17:26:47.831919    2938 plugins.go:71] No cloud provider specified.
I0720 17:26:47.831962    2938 start_node.go:289] Starting node minishiftvm (v1.3.0-alpha.2)
I0720 17:26:47.832605    2938 start_node.go:298] Connecting to API server https://10.0.2.15:8443
I0720 17:26:47.842481    2938 node.go:133] Connecting to Docker at unix:///var/run/docker.sock
I0720 17:26:47.886204    2938 node.go:376] Using iptables Proxier.
I0720 17:26:47.886268    2938 node.go:392] Tearing down userspace rules.
I0720 17:26:47.946206    2938 manager.go:132] cAdvisor running in container: "/"
I0720 17:26:47.984338    2938 node.go:448] Started Kubernetes Proxy on 0.0.0.0
I0720 17:26:47.989607    2938 fs.go:109] Filesystem partitions: map[/dev/sda1:{mountpoint:/mnt/sda1 major:8 minor:1 fsType: blockSize:0}]
I0720 17:26:48.012554    2938 machine.go:50] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0720 17:26:48.012594    2938 manager.go:169] Machine: {NumCores:2 CpuFrequency:4007996 MemoryCapacity:4142649344 MachineID: SystemUUID:4F39DFC5-D908-4D84-8D9C-346DB78958F0 BootID:d3d39527-5c88-4927-81a0-f574868e59a9 Filesystems:[{Device:/dev/sda1 Capacity:19195224064 Type:vfs Inodes:2436448}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:20971520000 Scheduler:deadline} 251:0:{Name:zram0 Major:251 Minor:0 Size:981958656 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:46:59:29:2c:50:7d Speed:0 Mtu:1500} {Name:eth0 MacAddress:08:00:27:9b:95:be Speed:1000 Mtu:1500} {Name:eth1 MacAddress:08:00:27:03:d1:64 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:8388608 Type:Unified Level:3}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:8388608 Type:Unified Level:3}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0720 17:26:48.030126    2938 manager.go:175] Version: {KernelVersion:4.4.14-boot2docker ContainerOsVersion:Boot2Docker 1.11.2 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016 DockerVersion:1.11.2 CadvisorVersion: CadvisorRevision:}
I0720 17:26:48.030638    2938 server.go:686] Watching apiserver
W0720 17:26:48.036311    2938 kubelet.go:510] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
I0720 17:26:48.036345    2938 kubelet.go:381] Hairpin mode set to "hairpin-veth"
I0720 17:26:48.063424    2938 manager.go:214] Setting dockerRoot to /mnt/sda1/var/lib/docker
I0720 17:26:48.111967    2938 node.go:347] Starting DNS on 10.0.2.15:53
I0720 17:26:48.112066    2938 log.go:11] skydns: ready for queries on cluster.local. for tcp://10.0.2.15:53 [rcache 0]
I0720 17:26:48.112073    2938 log.go:11] skydns: ready for queries on cluster.local. for udp://10.0.2.15:53 [rcache 0]
I0720 17:26:48.159018    2938 server.go:648] Started kubelet
I0720 17:26:48.159042    2938 server.go:108] Starting to listen on 0.0.0.0:10250
E0720 17:26:48.160589    2938 kubelet.go:958] Image garbage collection failed: unable to find data for container /
I0720 17:26:48.160890    2938 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0720 17:26:48.160905    2938 manager.go:123] Starting to sync pod status with apiserver
I0720 17:26:48.160920    2938 kubelet.go:2378] Starting kubelet main sync loop.
I0720 17:26:48.160924    2938 kubelet.go:2387] skipping pod synchronization - [container runtime is down]
E0720 17:26:48.168361    2938 manager.go:212] Docker container factory registration failed: docker found, but not using native exec driver.
I0720 17:26:48.168550    2938 factory.go:97] Registering Raw factory
I0720 17:26:48.176789    2938 manager.go:1003] Started watching for new ooms in manager
W0720 17:26:48.176860    2938 manager.go:243] Could not configure a source for OOM detection, disabling OOM events: exec: "journalctl": executable file not found in $PATH
I0720 17:26:48.177037    2938 manager.go:256] Starting recovery of all containers
I0720 17:26:48.177234    2938 manager.go:261] Recovery completed
I0720 17:26:48.301926    2938 kubelet.go:1183] Successfully registered node minishiftvm
I0720 17:26:49.188169    2938 nodecontroller.go:143] Sending events to api server.
I0720 17:26:49.213165    2938 replication_controller.go:208] Starting RC Manager
I0720 17:26:49.213189    2938 horizontal.go:125] Starting HPA Controller
I0720 17:26:49.213361    2938 controller.go:211] Starting Daemon Sets controller manager
W0720 17:26:49.263455    2938 nodecontroller.go:671] Missing timestamp for Node minishiftvm. Assuming now as a timestamp.
I0720 17:26:49.280008    2938 event.go:216] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"minishiftvm", UID:"minishiftvm", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node minishiftvm event: Registered Node minishiftvm in NodeController
I0720 17:26:49.478301    2938 start_master.go:632] Started Kubernetes Controllers
I0720 17:26:49.549290    2938 start_master.go:659] Started Origin Controllers
I0720 17:28:19.414532    2938 server.go:2161] http: multiple response.WriteHeader calls
I0720 17:29:36.800098    2938 server.go:2161] http: multiple response.WriteHeader calls
I0720 17:29:48.934273    2938 server.go:2161] http: TLS handshake error from 192.168.99.1:52017: remote error: unknown certificate authority
I0720 17:29:53.320062    2938 server.go:2161] http: multiple response.WriteHeader calls1
```

**Comment by gtirloni** [comment] 2016-07-20 17:45
![minishift_port](https://cloud.githubusercontent.com/assets/5902830/16996650/9a3871a2-4e88-11e6-9693-8a52a03adeb6.png)

**Comment by jorgemoralespou** [comment] 2016-07-21 07:43
Similar happens with mac and xhyve with 0.3.0.

````
[jmorales@mac-santander vagrant-origin.git] $minishift logs
==> /var/lib/minishift/openshift.err <==

==> /var/lib/minishift/openshift.out <==
W0721 07:34:39.605684    2373 start_master.go:271] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
W0721 07:34:39.605730    2373 start_master.go:271] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
I0721 07:34:39.610220    2373 admission.go:36] Admission plugin "ProjectRequestLimit" is not configured so it will be disabled.
I0721 07:34:39.610234    2373 admission.go:34] Admission plugin "PodNodeConstraints" is not configured so it will be disabled.
I0721 07:34:39.611675    2373 plugins.go:71] No cloud provider specified.
I0721 07:34:39.611688    2373 admission.go:30] Admission plugin "RunOnceDuration" is not configured so it will be disabled.
I0721 07:34:39.611702    2373 admission.go:34] Admission plugin "PodNodeConstraints" is not configured so it will be disabled.
I0721 07:34:39.611708    2373 admission.go:42] Admission plugin "ClusterResourceOverride" is not configured so it will be disabled.
I0721 07:34:39.612226    2373 genericapiserver.go:84] Adding storage destination for group
I0721 07:34:39.612240    2373 genericapiserver.go:84] Adding storage destination for group extensions
I0721 07:34:39.612256    2373 start_master.go:384] Starting master on 0.0.0.0:8443 (v1.3.0-alpha.2)
I0721 07:34:39.612260    2373 start_master.go:385] Public master address is https://192.168.64.3:8443
I0721 07:34:39.612271    2373 start_master.go:389] Using images from "openshift/origin-<component>:v1.3.0-alpha.2"
I0721 07:34:39.676472    2373 run.go:61] Started etcd at 192.168.64.3:4001
I0721 07:34:39.770839    2373 run_components.go:224] Using default project node label selector:
W0721 07:34:40.287495    2373 controller.go:262] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[]} [{[{192.168.64.3 <nil>}] [] [{https 8443 TCP} {dns 8053 UDP} {dns-tcp 8053 TCP}]}]}
I0721 07:34:40.777804    2373 trace.go:57] Trace "etcdHelper::Create *api.OAuthClient" (started 2016-07-21 07:34:40.468753433 +0000 UTC):
[31.02µs] [31.02µs] Object encoded
[31.888µs] [868ns] Version checked
[308.994491ms] [308.962603ms] Object created
[309.029638ms] [35.147µs] END
I0721 07:34:40.831625    2373 master.go:270] Started Kubernetes API at 0.0.0.0:8443/api/v1
I0721 07:34:40.831650    2373 master.go:270] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/extensions/v1beta1
I0721 07:34:40.831653    2373 master.go:270] Started Origin API at 0.0.0.0:8443/oapi/v1
I0721 07:34:40.831656    2373 master.go:270] Started OAuth2 API at 0.0.0.0:8443/oauth
I0721 07:34:40.831658    2373 master.go:270] Started Web Console 0.0.0.0:8443/console/
I0721 07:34:40.831661    2373 master.go:270] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
I0721 07:34:40.941883    2373 ensure.go:224] No cluster policy found.  Creating bootstrap policy based on: openshift.local.config/master/policy.json
I0721 07:34:43.841615    2373 ensure.go:209] Created default security context constraint privileged
I0721 07:34:43.864542    2373 ensure.go:209] Created default security context constraint nonroot
I0721 07:34:43.886809    2373 ensure.go:209] Created default security context constraint hostmount-anyuid
I0721 07:34:43.909478    2373 ensure.go:209] Created default security context constraint hostaccess
I0721 07:34:43.940221    2373 ensure.go:209] Created default security context constraint restricted
I0721 07:34:44.128920    2373 ensure.go:209] Created default security context constraint anyuid
I0721 07:34:44.163501    2373 ensure.go:209] Created default security context constraint hostnetwork
W0721 07:34:47.047214    2373 run_components.go:202] Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients
I0721 07:34:47.047566    2373 log.go:11] skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:8053 [rcache 0]
I0721 07:34:47.047581    2373 log.go:11] skydns: ready for queries on cluster.local. for udp4://0.0.0.0:8053 [rcache 0]
I0721 07:34:47.153049    2373 run_components.go:219] DNS listening at 0.0.0.0:8053
F0721 07:34:47.153213    2373 start_allinone.go:88] Server could not start: open openshift.local.config/node-minishiftvm/node-config.yaml: no such file or directory
````

**Comment by jimmidyson** [comment] 2016-07-21 07:50
Hmm. Can you `minishift ssh` & share the output of `sudo find /var/lib/minishift/` please?

**Comment by jorgemoralespou** [comment] 2016-07-21 07:51
Problem I think is node name:

````
docker@boot2docker:/mnt/sda1/var/lib/minishift/openshift.local.config$ ll
total 8
drwxr-xr-x    2 root     root          4096 Jul 21 07:34 master/
drwxr-xr-x    2 root     root          4096 Jul 21 07:34 node-boot2docker/
````

If you see in my output node name is node-minishift but in the dir is node-boot2docker.

**Comment by jimmidyson** [comment] 2016-07-21 07:53
Ah damn I remember now. The node name in xhyve is hardcoded to boot2docker... zchee/docker-machine-driver-xhyve#114.

@gtirloni Could you confirm the same on Windows please?

I'll fix this up ASAP & get a 0.3.1 release out.

**Comment by jorgemoralespou** [comment] 2016-07-21 08:06
@jimmidyson Now that I've seen the root cause, @gtirloni issue is different, since he's using VBox. Should I open a new issue for my problem to better track it, an leave the conversation here for he's issue? He's Brazil TZ so will take a while to anwer.

**Comment by jimmidyson** [comment] 2016-07-21 08:19
@jorgemoralespou Yeah it looks different - no need for a new issue, fixing it up now for you & will continue discussion with @gtirloni here. Thanks anyway!

**Comment by jajansen** [comment] 2016-07-22 06:51
Having the same problem as @gtirloni on Windows 10 and VirtualBox. It looks to me that the API server is binding to the wrong (NAT) network adapter instead of the Host-Only adapter
```
$ ./minishift.exe ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.11.2, build master : 901340f - Fri Jul  1 22:52:19 UTC 2016
Docker version 1.11.2, build b9f10c9
docker@minishiftVM:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:DD:AB:BE:B0
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:89:65:FB
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe89:65fb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:98074 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11885 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:145674175 (138.9 MiB)  TX bytes:890295 (869.4 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:10:16:9F
          inet addr:192.168.99.102  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe10:169f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4653 errors:0 dropped:0 overruns:0 frame:0
          TX packets:124 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:437266 (427.0 KiB)  TX bytes:48028 (46.9 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:512932 errors:0 dropped:0 overruns:0 frame:0
          TX packets:512932 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:93538370 (89.2 MiB)  TX bytes:93538370 (89.2 MiB)

docker@minishiftVM:~$
```

**Comment by jimmidyson** [comment] 2016-07-22 06:55
It's binding to all interfaces but looks like it's selecting the internal iface for the console canonical address.

**Comment by xloggerster** [comment] 2016-08-19 03:37
I think I was getting similar issue... I'm running minishift 0.3.2 on windows7. 
    minishift start --memory=6000 --vm-driver=virtualbox
    
the minishift VM was started, "oc login" success, "oc run hello-openshift..." returns success with the pod showing in "oc get pods" 

but accessing https://192.168.99.1:8443/console/ or curl $(minishift service hello-minishift --url) failed. from the browser trace I was redirected to 10.0.2.15... which is unreachable

**Comment by kadel** [comment] 2016-08-24 16:41
I have same issue on Linux when using Virutalbox. Console is redirecting to 10.0.2.xx which in unreachable from host machine.

**Comment by jimmidyson** [comment] 2016-08-24 16:53
OK I'll look at fixing that up - should be just a case of configuring OpenShift public URL appropriately.

**Comment by jimmidyson** [comment] 2016-08-24 17:02
Fixed in #56 - will merge & then release 0.4.1

**Comment by jimmidyson** [comment] 2016-08-24 17:04
BTW I will generally advise using anything other than virtualbox (unless you're super happy with it). Other solutions seem to work better & use less resources for me, e.g. KVM on Linux, xhyve on OS X, hyper-v on Windows >=10. But don't worry: we will continue to support virtualbox going forwards for those that want to use it.

**Closed** 2016-08-24 17:10 UTC
Labels: bug, windows

**Comment by gtirloni** [comment] 2016-08-24 17:12
@jimmidyson unfortunately vagrant is a bit part of our workflow and its support for vmware is on a best effort basis (even with the paid plugin). that's basically why i'm stuck with virtualbox. i do have a license for vmware workstation that i barely use which makes me sad (its 3d acceleration is awesome).

**Comment by jimmidyson** [comment] 2016-08-24 17:15
@gtirloni I understand. If you're on Windows 10 have you tried Vagrant with hyperv? I'm not a Windows user but I've heard good things about it.

**Comment by gtirloni** [comment] 2016-08-24 17:19
@jimmidyson that's what we are hoping for: to use hyper-v and xhyve soon, but we haven't tried that yet. it looks like the best way forward now that docker for win/mac is using them. let's see.. we have a complicated pipeline here with developers using a multitude of platforms (which reminds me some refuse to move from windows 7 *cries* *cries some more*).

**Comment by jimmidyson** [comment] 2016-08-24 17:22
@gtirloni No need for tears, the future can only get better :stuck_out_tongue_winking_eye:
